apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrelease-cert-manager.yaml
- helmrelease-cert-manager-config.yaml
- helmrelease-falco.yaml
- helmrelease-ingress-nginx.yaml
- helmrelease-kube-opex-analytics.yaml
- helmrelease-logging.yaml
- helmrelease-linkerd.yaml
- helmrelease-loki.yaml
- helmrelease-monitoring.yaml
- helmrelease-monitoring-config.yaml
- helmrelease-starboard.yaml
- helmrelease-teleport-agent.yaml
- helmrelease-velero.yaml
- helmrelease-velero-config.yaml
- helmrepository.yaml
